---

- hosts: all
  become: true
  pre_tasks: 

  - name: update repository index
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: webservers
  become: true
  tasks:
  
  - name: install apache2 and php packages
    tags: ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache, ubuntu
    copy: 
      src: default_site.html
      dest: /var/www/html/index53.html
      owner: root
      group: root
      mode: 0644

  - name: Make sure apache2 is started
    tags: apstart
    ansible.builtin.sysvinit:
      name: apache2
      state: started
      enabled: yes

